apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbacResourcesName }}
  labels: {{- include "qlkube.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - crownlabs.polito.it
    resources:
      - instances
      - instances/status
      - instancesnapshots
      - instancesnapshots/status
      - templates
      - templates/status
      - workspaces
      - workspaces/status
      - tenants
      - tenants/status
    verbs:
      - get
      - list
      - watch
