# Default values for qlkube.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: crownlabs/qlkube
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

deploymentAnnotations: {}
podAnnotations: {}

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  privileged: false

service:
  type: ClusterIP
  port: 8080

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/custom-http-errors: "418"
  hostname: qlkube.crownlabs.example.com
  path: /
  secret: qlkube-certificate

resources:
  limits:
    cpu: 1000m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 250Mi

rbacResourcesName: crownlabs-qlkube